name: NASA Project CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa

    strategy:
      matrix:
        node-version: [22.x]   # use only modern stable version
        mongodb-version: ['4.4']  # simplify versioning

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upgrade npm (compatible version)
        run: npm install -g npm@8.19.4

      - name: Use MongoDB from GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install server dependencies
        working-directory: ./server2
        run: npm install

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Run tests
        working-directory: ./server2
        run: npm test
